### ISSUE TITLE
Failed to load personal profile

### ISSUE THREAD

**Issue by reality-exe** [Nutcake/contacts-plus-plus#19]
Personal profile fails to load.

Don't know if this just isnt implemented yet or not.

**Comment by Nutcake** [comment]
This should be fixed in v1.2.1, let me know if it works for you now.

**Comment by reality-exe** [comment]
Nope, still wont load.

If it helps any i'm on a rooted Pixel 6

**Comment by Nutcake** [comment]
Alright, let's give it another shot, could you try again with v1.2.2?

**Comment by reality-exe** [comment]
Still ain't working.

Is there a way to get logs?

**Comment by Nutcake** [comment]
The problem with loggin is that for logs to be truly useful in situations like this I need them to contain exact server responses which could contain potentially sensitive data like private messages and email addresses etc. I haven't quite decided yet how I want to deal with this, in the meantime could you install this debug version of the app and take a screenshot of the error you get?

[contacts_plus_plus-v1.2.2-testing.zip](https://github.com/Nutcake/contacts-plus-plus/files/11492151/contacts_plus_plus-v1.2.2-testing.zip)

Thank you for helping me debug this!

**Comment by reality-exe** [comment]
![Screenshot_20230516-211334.png](https://github.com/Nutcake/contacts-plus-plus/assets/95439036/9bab9f48-4d6f-486c-8fe2-2f272611a229)

**Comment by Nutcake** [comment]
Interesting, I knew the list of storage extensions could be empty, I didn't expect them to ever be null.

This version should fix the issue.
[contacts_plus_plus-v1.2.3.zip](https://github.com/Nutcake/contacts-plus-plus/files/11494794/contacts_plus_plus-v1.2.3.zip)

**Comment by reality-exe** [comment]
It works now!

Gotta love it when random things pop up lol
